
spring:
  application:
    name: listo
  datasource:
    url: jdbc:h2:mem:listo
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console


greeting:
  message: Welcome to Listo!!!

logging:
  level:
    com.msa.user: DEBUG

token:
  secret: listo
  expire: 86400000